### PR TITLE
fix Dockerfile-mpi download miniconda.sh

### PR DESCRIPTION
**Pull request by jiaqianjing**
(curl -o -O) it's not work when I built image of mpi at aliyun

### CODE REVIEW

**Comment by gaocegege** [comment]
Can you show us more info about it? Will it return an error?

**Comment by jiaqianjing** [comment]
> Can you show us more info about it? Will it return an error?

image

**Comment by jiaqianjing** [comment]
And another question when I built image for mpi:
image

**Comment by gaocegege** [comment]
@jiaqianjing 
Thanks for your contribution! :tada: :+1:

**Pull request merged**
