### PR TITLE
Migrate to new test-infra

### PR DESCRIPTION
**Pull request by PatrickXYS**
**Which issue is resolved by this Pull Request:**
Part of https://github.com/kubeflow/testing/issues/861

**Description of your changes:**
Start from migrating pytorch-operator first

### CODE REVIEW

**Comment by Jeffwan** [comment]
@PatrickXYS What's the recent change?

**Comment by PatrickXYS** [comment]
@Jeffwan There's no change in testing itself, only migrate from old test-infra to new test-infra.

**Comment by PatrickXYS** [comment]
```
  Warning  Failed     104s   kubelet            Error: failed to start container "test": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: setenv: invalid argument: unknown
```

Seems like it's related to encoded secret https://github.com/opencontainers/runc/issues/1720

**Comment by PatrickXYS** [comment]
```
subprocess.CalledProcessError: Command 'cmd: ks-13 apply kubeflow-pytorch-operator-presubmit-e2e-316-b2e6905-7312-e89b -c workflows exited with code 1' returned non-zero exit status 1.
```

Argo workflow has been generated, and apply failed to work. Checking

**Comment by PatrickXYS** [comment]
Not sure if this is one-off error, kicking off to see how it goes 


/test kubeflow-pytorch-operator-presubmit
--

**Comment by PatrickXYS** [comment]
I see, it should be caused by IAM role does not have access to the argo cluster

**Comment by PatrickXYS** [comment]
Succeeded in creating Argo workflow in argo cluster

```
# ks-13 apply pytorch-test-e2e-316-b2e6905-9e68 -c workflows
INFO Applying workflows kubeflow-test-infra.pytorch-test-e2e-316-b2e6905-9e68
INFO Creating non-existent workflows kubeflow-test-infra.pytorch-test-e2e-316-b2e6905-9e68
```

**Comment by PatrickXYS** [comment]
@Jeffwan  I forgot to mention that we should help WG create ECR registry in new AWS account in advance

**Comment by PatrickXYS** [comment]
image

Ref: https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-pytorch-operator-presubmit-e2e-316-6defc74-8208-14a8?tab=workflow&nodeId=kubeflow-pytorch-operator-presubmit-e2e-316-6defc74-8208-14a8-1546001585

Succeeded as expected

**Comment by PatrickXYS** [comment]
This travis-ci is queued for resources... It might be better to use GitHub actions for simple tests

**Comment by Jeffwan** [comment]
/lgtm
/approve

Thanks. Let me know anything I can help.

**Comment by PatrickXYS** [comment]
Not sure why the argo_endpoint still point to the old one, checked it locally and it's referring to new one in my local machine.

image

**Comment by PatrickXYS** [comment]
I see, the run_workflow.sh is embedded into image

https://github.com/kubeflow/testing/blob/master/images/Dockerfile.py3.aws#L83-L84

Need to rebuild the test-worker image

**Comment by PatrickXYS** [comment]
It works after re-build test-worker image

image

**Comment by PatrickXYS** [comment]
/cc @Jeffwan 

Should be good to go

**Pull request merged**
