### PR TITLE
Generate Kubeflow PyTorchJob SDK

### PR DESCRIPTION
**Pull request by jinchihe**
Discussed in https://github.com/kubeflow/tf-operator/issues/167, and requried by @johnugeorge.

### The PR is includes:
- Generated PyTorchJob Python SDK from the way: Go type -> openapi -> swagger file -> PyTorch SDK.
- Manually update the SDK name to `kubeflow-pytorchjob` and  `from kubeflow import pytorchjob`.
- Manually added some Client APIs such as create, get, update, delete ...
- Release frist version `kubeflow-pytorch` SDK to Pypi: https://pypi.org/project/kubeflow-pytorchjob/
- Drafted some docs and updated Readme file.
- Created a sample for the SDK usage.
- Added some CI tests for the SDK.
- Work around some testing problem below.

### Next: 
- Need to add more APIs for the SDK.
- Need to update CI tests due to https://github.com/kubeflow/pytorch-operator/issues/229

### CODE REVIEW

**Comment by jinchihe** [comment]
Failed to set kubeflow in CI test.
```
level=error msg="validating registry URL: validating GitHub registry URL: \"https://github.com/kubeflow/kubeflow/tree/master/kubeflow/reg
istry.yaml\" actual 404; expected 200"
```

**Comment by jinchihe** [comment]
/assign @johnugeorge @gaocegege 
/cc @animeshsingh @richardsliu @jlewi 

The PR is ready for reviewing now, please see the PR description section for details. Thanks a lot!

**Comment by johnugeorge** [comment]
Looks great. Thanks @jinchihe for this contribution

**Pull request merged**
