### PR TITLE
Add more APIs for SDK

### PR DESCRIPTION
**Pull request by jinchihe**
From feedback, as done for  the `kubeflow-tfjob` SDK, add more APIs for `kubeflow-pytorchjob`:

- `wait_for_job`: Wait for the specified job to finish 
- `wait_for_condition`: Waits until any of the specified conditions occur
- `get_job_status`: Quick way to get the PyTorchJob status
- `is_job_running`: Quick way to check if the PyTorchJob status is Running
- `is_job_succeeded`:  Quick way to check if the PyTorchJob status is Succeeded

### CODE REVIEW

**Comment by jinchihe** [comment]
/cc @gaocegege @johnugeorge 
Could you please take a look? Thanks a lot!

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by johnugeorge** [comment]
Great. 
Do you think, if `is_job_running` makes more sense than `if_job_running`?  Similarly for `if_job_succeeded`   ?

**Comment by jinchihe** [comment]
@johnugeorge Great comments. Agree with you, `is_job_running` better than `if_job_running`, I'm going to update, and I'm also going to update TFJob side. Thanks!

**Comment by jinchihe** [comment]
@johnugeorge Updated, Thanks.

**Comment by johnugeorge** [comment]
@jinchihe Can you please update the PR comment too to reflect the new function names - https://github.com/kubeflow/pytorch-operator/pull/240#issue-354018739

**Comment by jinchihe** [comment]
> @jinchihe Can you please update the PR comment too to reflect the new function names - [#240 (comment)](https://github.com/kubeflow/pytorch-operator/pull/240#issue-354018739)

Updated, thanks!

**Comment by johnugeorge** [comment]
Thanks @jinchihe 
/approve

**Pull request merged**
