### PR TITLE
Add watch function for PyTorchJob python Client API

### PR DESCRIPTION
**Pull request by jinchihe**
Add watch function for the PyTorchJob python API to watch key info, such as status, like `kubeflow get pytorchjob`. 
The PR is going to add watch function (added one more option `watch=Flase`) for PyTorchJob python Client `get()` and `waiting_for_job()` API, as below:

```
pytorch_client = PyTorchJobClient()
pytorch_client.wait_for_job('pytorch-dist-mnist-gloo', watch=True)
NAME                           STATE                TIME                          
pytorch-dist-mnist-gloo        Created              2020-01-02T09:37:48Z          
pytorch-dist-mnist-gloo        Running              2020-01-02T09:37:58Z          
pytorch-dist-mnist-gloo        Running              2020-01-02T09:37:58Z          
pytorch-dist-mnist-gloo        Running              2020-01-02T09:37:58Z          
pytorch-dist-mnist-gloo        Running              2020-01-02T09:37:58Z          
pytorch-dist-mnist-gloo        Running              2020-01-02T09:37:58Z          
pytorch-dist-mnist-gloo        Running              2020-01-02T09:37:58Z          
pytorch-dist-mnist-gloo        Succeeded            2020-01-02T09:42:47Z          

```

Due to CI tests failed while verifying code-gen, I also updated related files. Thanks.

### CODE REVIEW

**Comment by johnugeorge** [comment]
Can you make similar changes that you added for tf operator?

**Comment by jinchihe** [comment]
> Can you make similar changes that you added for tf operator?

Yes, I'm going to do similar functions as for TFJob Python API. Thanks @johnugeorge

**Comment by johnugeorge** [comment]
Once you remove WIP status, I can review.
Thanks for your contribution

**Comment by jinchihe** [comment]
> Once you remove WIP status, I can review.

@johnugeorge Great thanks! That's ready for reviewing now.

**Comment by johnugeorge** [comment]
Thanks
/lgtm

**Pull request merged**
