### PR TITLE
add mnist example dockerfile for ppc64le

### PR DESCRIPTION
**Pull request by zheddie**
/cc @jinchihe @hougangliu 
I corrected the username issue. Please help to review this request. thanks.

### CODE REVIEW

**Comment by johnugeorge** [comment]
@zheddie

**Comment by jinchihe** [comment]
@zheddie Could you please also update Readme file as @gaocegege commented? Thanks.

**Comment by zheddie** [comment]
@jinchihe @gaocegege , README.md  was updated , please help to review. Thanks.

**Comment by hougangliu** [comment]
/lgtm
Thanks

**Pull request merged**
