### PR TITLE
Adding examples for v1 api

### PR DESCRIPTION
**Pull request by johnugeorge**
Related: #160

### CODE REVIEW

**Comment by richardsliu** [comment]
Can you also update https://github.com/kubeflow/pytorch-operator/blob/master/README.md?

**Comment by johnugeorge** [comment]
@richardsliu done

**Comment by johnugeorge** [comment]
https://github.com/kubeflow/pytorch-operator/pull/165 has to be merged first since v1beta1 support is removed  from the ksonnet package.

**Pull request merged**
