### PR TITLE
update pytorch-operator deployment manifests file

### PR DESCRIPTION
**Pull request by myonlyzzy**
fix [issue294](https://github.com/kubeflow/pytorch-operator/issues/294)

### CODE REVIEW

**Comment by gaocegege** [comment]
Please sign Google CLA.

**Comment by myonlyzzy** [comment]
@googlebot I fixed it

**Comment by myonlyzzy** [comment]
@googlebot I fixed it

**Comment by myonlyzzy** [comment]
@gaocegege @johnugeorge  google cla has been signed.

**Comment by gaocegege** [comment]
/approve 

Thanks for your contribution! :tada: :+1:

**Comment by Jeffwan** [comment]
You will need to rebase the master change to make test go through. @myonlyzzy 
Can you help do that and then I can approve the change

**Pull request merged**
