### PR TITLE
Adding e2e tests for v1beta1

### LINKED ISSUE #86: Refactor E2E tests
More E2E tests have to be added test/e2e/v1alpha2/  into as per doc https://docs.google.com/document/d/1OLPp0gMPvBfwDs70Xf4tMS2qqtlR3nKu9P4B7FvlJ9M/edit#

### PR DESCRIPTION
**Pull request by johnugeorge**
Adding e2e tests for v1beta1

Fixes #86 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pytorch-operator/101)

### CODE REVIEW

**Comment by richardsliu** [comment]
Is there any chance we can leverage the e2e test framework defined in tf-operator? Then it would be easy for contributors to start adding tests.

**Comment by johnugeorge** [comment]
@richardsliu I have created a separate issue for it. It might take some time to adapt to it. I will work on it. Meanwhile we can use these tests for current PRs. what do you think?

**Pull request merged**
