### PR TITLE
Move PyTorch Operator e2e tests to AWS Prow

### PR DESCRIPTION
**Pull request by Jeffwan**

### CODE REVIEW

**Comment by Jeffwan** [comment]
sdk test failure:

```
 ls /usr/local/lib/py*
/usr/local/lib/python3.6:
dist-packages

/usr/local/lib/python3.8:
dist-packages

```

table_logger actually is installed in 3.6. however, we have two python envs in the package and `pytest` use 3.8 which doesn't have dependency

**Comment by PatrickXYS** [comment]
> @PatrickXYS: No presubmit jobs available for kubeflow/pytorch-operator@master

This still suffices even though we don't have Upstream Prow Prsubmit Enabled

**Comment by andreyvelich** [comment]
@Jeffwan @PatrickXYS Can you add LGTM on this PR: https://github.com/kubeflow/pytorch-operator/pull/293, please?
That should fix travis unit test.

**Comment by Jeffwan** [comment]
I think the only one left is we want aws-bot report test status on the PR. Besides that, everything looks good to me

**Comment by andreyvelich** [comment]
@Jeffwan Yes.
Try to rebase to fix unit tests

**Review by gaocegege — COMMENTED** [review]
/approve

**Pull request merged**
