### PR TITLE
Update manifest to latest

### PR DESCRIPTION
**Pull request by hougangliu**
Update manifest to latest, making easy to test or develop pytorch-operator

### CODE REVIEW

**Comment by johnugeorge** [comment]
@hougangliu I can ask someone to create a v1.0 tag for the image. I will update it here once done

**Comment by hougangliu** [comment]
> @hougangliu I can ask someone to create a v1.0 tag for the image. I will update it here once done

cool. Close this PR now

**Comment by johnugeorge** [comment]
I meant, we can use 1.0 tag for the pytorch operator in the manifests(instead of rc image) when created.  We can use this same PR for updating the manifests

**Comment by hougangliu** [comment]
ok,  I will re-create the PR with 1.0 tag

**Pull request closed without merging**
