### PR TITLE
set CompletionTime first when pytorchjob exceeds limit

### PR DESCRIPTION
**Pull request by wackxu**
ref https://github.com/kubeflow/tf-operator/issues/994

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pytorch-operator/158)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Thanks for your first PR. Can you fix the travis issue?

**Comment by johnugeorge** [comment]
@wackxu

**Comment by wackxu** [comment]
@johnugeorge Done

**Pull request merged**
