### PR TITLE
Remove unnecessary services for worker

### PR DESCRIPTION
**Pull request by hougangliu**
For pytorchJob, MASTER_PORT and MASTER_ADDR are necessary. andMASTER_PORT will be occupied only in `Master` Pod. 

In master Pod, it will
1. Creates sockets for all workers.
2. Waits for all workers to connect.
3. Sends them information about the location of the other processes.

all worker Pods will
1. creates a socket to MASTER_ADDR (master service name): MASTER_PORT
2. send their own location information (**ip:randomPort**).
3. Receives information about the other workers.
4. Opens a socket and handshakes with all other workers.

That is, MASTER_PORT on worker will not be used. Services for all workers is unnecessary.

### CODE REVIEW

**Comment by gaocegege** [comment]
If the worker does not expose port, how can they `Opens a socket and handshakes with all other workers.`

**Comment by hougangliu** [comment]
> If the worker does not expose port, how can they `Opens a socket and handshakes with all other workers.`

In fact, in a container, even port is not exposed explicitly. we can still visit it by "podIP:port"

**Comment by gaocegege** [comment]
@hougangliu 

Yeah, I know. Thus what will happen if there is a worker pod failed. The IP will be changed.

**Comment by hougangliu** [comment]
> Yeah, I know. I am wondering what will happen if there is a worker pod failed. The IP will be changed.

Once when a worker Pod failed, the PytorchJob restarts.

**Comment by gaocegege** [comment]
Yeah, the operator will restart the pod, but the pod IP may change. Can we handle the IP change in the PR?

**Comment by hougangliu** [comment]
> Yeah, the operator will restart the pod, but the pod IP may change. Can we handle the IP change in the PR?

We don't need handle it. When new Pod created, it will register its `NewPodIP:NewPort` to `MASTER_ADDR (master service name): MASTER_PORT` by call Initialization method in pytorch source code.

**Comment by gaocegege** [comment]
OK, then LGTM.

/lgtm

I am not familiar with Distributed Training in PyTorch.

So, /assign @johnugeorge

**Comment by johnugeorge** [comment]
Just wondering if you have faced some issue without this PR?  Or is it just a cleanup? 

@gaocegege How is this different from distributed TF?

**Comment by hougangliu** [comment]
> Just wondering if you have faced some issue without this PR? Or is it just a cleanup?
> 
> @gaocegege How is this different from distributed TF?
This is just for cleanup, all worker services in fact are unused. We can drop them.
tensorflow builds distribution-cluster by `hostname+port` list explicitly, but for pytorch, they only need a service (MASTER_ADDR: MASTER_PORT) to register all workers to generate a cluster. They build cluster in different ways

**Comment by gaocegege** [comment]
> tensorflow builds distribution-cluster by hostname+port list explicitly, but for pytorch, they only need a service (MASTER_ADDR: MASTER_PORT) for workers, all workers will register itself to the service to generate a cluster. They build cluster in different ways

I think it is the difference. @johnugeorge

**Comment by johnugeorge** [comment]
Got it.

/approve

**Pull request merged**
