### PR TITLE
Update manifest to v0.6.0

### PR DESCRIPTION
**Pull request by hougangliu**
Update manifest to latest, making easy to test or develop pytorch-operator

### CODE REVIEW

**Comment by johnugeorge** [comment]
@hougangliu Image tag v0.6.0 is created. 
Can you use image tag pytorch-operator:v0.6.0 in this PR?

**Comment by hougangliu** [comment]
> @hougangliu Image tag v0.6.0 is created.
> Can you use image tag pytorch-operator:v0.6.0 in this PR?

sure. done!
Thanks

**Comment by johnugeorge** [comment]
Thanks @hougangliu

**Comment by johnugeorge** [comment]
https://status.coveralls.io coveralls is down

**Pull request merged**
