### PR TITLE
Adding tests for v1beta2

### PR DESCRIPTION
**Pull request by johnugeorge**
Testing infra code #127  has to be updated once this is merged

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pytorch-operator/143)

### CODE REVIEW

**Comment by richardsliu** [comment]
/lgtm
For my own curiosity, do we have plans to move to Python based e2e tests like in tf-operator?

**Comment by johnugeorge** [comment]
@richardsliu Yes. @Akado2009 has started work in #127 Hope It will get completed very soon.

**Pull request merged**
