### PR TITLE
pytorch-operator: Consolidate manifests

### PR DESCRIPTION
**Pull request by yanniszark**
Umbrella-Issue: https://github.com/kubeflow/manifests/issues/1769

#### Current manifests structure

```
.
├── crd.yaml
├── deployment.yaml
├── kustomization.yaml
├── namespace.yaml
├── podgroup.yaml
├── pytorch-job-crds
│   ├── base
│   └── overlays
│       └── application
├── pytorch-operator
│   ├── base
│   └── overlays
│       └── application
```

#### Explanation

- `pytorch-job-crds` and `pytorch-job-operator` came from kubeflow/manifests.
- The other files were the existing kustomization in the upstream repo.
- The `application` overlays contain Application CRs, which we want to move away from (https://github.com/kubeflow/manifests/issues/1715#issuecomment-779402779)

#### Recommended end state

The main diff is that the upstream manifests also install a namespace resource, which we don't want when installing with kubeflow. Following the standard `base` and `overlays` structure, I propose the following structure:
```.
├── base
├── overlays
│   ├── kubeflow
│   └── standalone
```
- `overlays/standalone` is used to install the operator in its own namespace, for testing or other purposes.
- `overlays/kubeflow` is used to install the operator as part of kubeflow.

### CODE REVIEW

**Comment by Jeffwan** [comment]
See #325 for more details. I file #326 to mitigate this issue. This should be unblocked once #326  is merged

**Comment by yanniszark** [comment]
I have rebased and the tests now pass. Thanks @Jeffwan

**Review by Jeffwan — APPROVED** [review]

**Pull request merged**
