### PR TITLE
Support manifest on Kubernetes 1.16+

### PR DESCRIPTION
**Pull request by Jeffwan**
Update Deployment apiVersion from `extensions/v1beta1` to `apps/v1`

### CODE REVIEW

**Comment by Jeffwan** [comment]
/cc @johnugeorge @gaocegege

Let's merge some pending PRs.

**Review by andreyvelich — COMMENTED** [review]
/lgtm

**Comment by Jeffwan** [comment]
PR https://github.com/kubeflow/pytorch-operator/pull/305 already includes this PR. I will close the issue

**Pull request closed without merging**
