### PR TITLE
Unstructured converted to Pytorch Job Anonymous field error when json uses inline mode

### PR DESCRIPTION
**Pull request by leileiwan**
for issue https://github.com/kubeflow/pytorch-operator/issues/234

### CODE REVIEW

**Comment by leileiwan** [comment]
> Is the change hand-written?

yes，I changed the function structFromUnstructured by myself

**Comment by gaocegege** [comment]
I think we should not update the vendor manually. When we use godep generate the vendor, the change will be overwritten.

**Comment by leileiwan** [comment]
> I think we should not update the vendor manually. When we use godep generate the vendor, the change will be overwritten.

I know，but apimachinery seen to have a little bug. How can I better fix this bug in my own project ？

**Comment by johnugeorge** [comment]
It is better to fix it upstream.

**Comment by leileiwan** [comment]
> It is better to fix it upstream.

Ok，I wil close the PR

**Pull request closed without merging**
