### PR TITLE
feat(init_container): Add init container image CLI argument

### LINKED ISSUE #261: [feature] Support CLI argument for init container image
Now we only support to define the image in the template, I think it will be better if we could support it with an argument `-init-container-image busybox:1.30.0`

### PR DESCRIPTION
**Pull request by gaocegege**
Fix #261 

Signed-off-by: Ce Gao <gaoce@caicloud.io>
```
  -init-container-image string
    	The image of the injected init container, will overwrite the value in config (default "alpine:3.10")
```

### CODE REVIEW

**Comment by johnugeorge** [comment]
@gaocegege Can't you override the whole initContainerTemplate? 
https://github.com/kubeflow/pytorch-operator/blob/master/pkg/common/config/config.go#L23

What is your requirement?

**Comment by gaocegege** [comment]
@johnugeorge The template yaml should be defined in build time. We need to update the image name in runtime.

**Comment by johnugeorge** [comment]
Just wondering if mounting ConfigMap on a volume path doesn't work for you?

**Comment by gaocegege** [comment]
We can but prefer to keep flexibility. I just want to update the image and do not want to maintain a different template.

**Comment by johnugeorge** [comment]
SGTM
/lgtm

**Pull request merged**
